name: "move_files_to_directory"
version: "main"
authors:
- name: "Dorien Roosen"
  roles:
  - "maintainer"
  info:
    links:
      email: "dorien@data-intuitive.com"
      github: "dorien-er"
      linkedin: "dorien-roosen"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Data Scientist"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input"
    description: "Paths of the files that will be copied into the output directory."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    description: "Path to output directory"
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "boolean_true"
    name: "--keep_symbolic_links"
    alternatives:
    - "-d"
    description: "Preserve symbolic links."
    info: null
    direction: "input"
resources:
- type: "bash_script"
  path: "script.sh"
  is_executable: true
summary: "Publish one or multiple files to the same directory"
description: "This component copies one or multiple files to the same destination\
  \ directory, creating the output directory if it doesn't exist."
test_resources:
- type: "bash_script"
  path: "test.sh"
  is_executable: true
info: null
status: "enabled"
scope:
  image: "public"
  target: "public"
requirements:
  commands:
  - "ps"
license: "MIT"
links:
  repository: "https://github.com/viash-hub/craftbox"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1000000000.B"
      mem2gb: "memory = 2000000000.B"
      mem5gb: "memory = 5000000000.B"
      mem10gb: "memory = 10000000000.B"
      mem20gb: "memory = 20000000000.B"
      mem50gb: "memory = 50000000000.B"
      mem100gb: "memory = 100000000000.B"
      mem200gb: "memory = 200000000000.B"
      mem500gb: "memory = 500000000000.B"
      mem1tb: "memory = 1000000000000.B"
      mem2tb: "memory = 2000000000000.B"
      mem5tb: "memory = 5000000000000.B"
      mem10tb: "memory = 10000000000000.B"
      mem20tb: "memory = 20000000000000.B"
      mem50tb: "memory = 50000000000000.B"
      mem100tb: "memory = 100000000000000.B"
      mem200tb: "memory = 200000000000000.B"
      mem500tb: "memory = 500000000000000.B"
      mem1gib: "memory = 1073741824.B"
      mem2gib: "memory = 2147483648.B"
      mem4gib: "memory = 4294967296.B"
      mem8gib: "memory = 8589934592.B"
      mem16gib: "memory = 17179869184.B"
      mem32gib: "memory = 34359738368.B"
      mem64gib: "memory = 68719476736.B"
      mem128gib: "memory = 137438953472.B"
      mem256gib: "memory = 274877906944.B"
      mem512gib: "memory = 549755813888.B"
      mem1tib: "memory = 1099511627776.B"
      mem2tib: "memory = 2199023255552.B"
      mem4tib: "memory = 4398046511104.B"
      mem8tib: "memory = 8796093022208.B"
      mem16tib: "memory = 17592186044416.B"
      mem32tib: "memory = 35184372088832.B"
      mem64tib: "memory = 70368744177664.B"
      mem128tib: "memory = 140737488355328.B"
      mem256tib: "memory = 281474976710656.B"
      mem512tib: "memory = 562949953421312.B"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "debian:latest"
  target_registry: "images.viash-hub.com"
  target_tag: "main"
  namespace_separator: "/"
  setup:
  - type: "apt"
    packages:
    - "procps"
    interactive: false
  entrypoint: []
  cmd: null
- type: "native"
  id: "native"
build_info:
  config: "src/move_files_to_directory/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker|native"
  output: "target/nextflow/move_files_to_directory"
  executable: "target/nextflow/move_files_to_directory/main.nf"
  viash_version: "0.9.4"
  git_commit: "952e20a6a88b08cfb46a57bfdb228d82c01e4748"
  git_remote: "https://github.com/viash-hub/craftbox"
  git_tag: "v0.1.0-8-g952e20a"
package_config:
  name: "craftbox"
  version: "main"
  summary: "A collection of custom-tailored scripts and applied utilities built with\
    \ Viash.\n"
  description: "`craftbox` is a curated collection of custom scripts and utilities\
    \ designed to tackle context-specific tasks.\n\nEmphasizing the Viash principles,\
    \ `craftbox` components aim for **reusability**, **reproducibility**, and adherence\
    \ to **best practices**. Key features generally include:\n\n* **Standalone & Nextflow\
    \ Ready:** Components are built to run directly via the command line or be smoothly\
    \ integrated into Nextflow workflows.\n* **Custom Implementations:** Contains\
    \ scripts and tools developed for particular tasks that may not be found in broader\
    \ collections.\n* **High Quality Standards (promoted by Viash):**\n    * Clear\
    \ documentation for components and their parameters.\n    * Full exposure of underlying\
    \ script/tool arguments for fine-grained control.\n    * Containerized (Docker)\
    \ to ensure dependency management and a consistent, reproducible runtime environment.\n\
    \    * Unit tested where applicable to ensure components function as expected.\n"
  info: null
  viash_version: "0.9.4"
  source: "src"
  target: "target"
  config_mods:
  - ".requirements.commands := ['ps']\n"
  - ".engines += { type: \"native\" }"
  - ".engines[.type == 'docker'].target_registry := 'images.viash-hub.com'"
  - ".engines[.type == 'docker'].target_tag := 'main'"
  keywords:
  - "scripts"
  - "custom"
  - "implementations"
  - "utilities"
  license: "MIT"
  organization: "vsh"
  links:
    repository: "https://github.com/viash-hub/craftbox"
    issue_tracker: "https://github.com/viash-hub/craftbox/issues"
