name: "h5mu_to_qc_json"
namespace: "ingestion_qc"
version: "build_main"
authors:
- name: "Jakub Majercik"
  roles:
  - "author"
  info:
    role: "Contributor"
    links:
      email: "jakub@data-intuitive.com"
      github: "jakubmajercik"
      linkedin: "jakubmajercik"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Bioinformatics Engineer"
- name: "Dorien Roosen"
  roles:
  - "author"
  info:
    role: "Core Team Member"
    links:
      email: "dorien@data-intuitive.com"
      github: "dorien-er"
      linkedin: "dorien-roosen"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Data Scientist"
- name: "Robrecht Cannoodt"
  roles:
  - "author"
  info:
    role: "Core Team Member"
    links:
      email: "robrecht@data-intuitive.com"
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
      linkedin: "robrechtcannoodt"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Data Science Engineer"
    - name: "Open Problems"
      href: "https://openproblems.bio"
      role: "Core Member"
- name: "Weiwei Schultz"
  roles:
  - "contributor"
  info:
    role: "Contributor"
    organizations:
    - name: "Janssen R&D US"
      role: "Associate Director Data Sciences"
argument_groups:
- name: "Inputs"
  arguments:
  - type: "file"
    name: "--input"
    description: "The input h5mu file(s)"
    info: null
    example:
    - "path/to/file.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--modality"
    description: "The modality to use"
    info: null
    default:
    - "rna"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--ingestion_method"
    description: "Method that was used to ingest the data - this will define the structure\
      \ of the report that is generated."
    info: null
    required: true
    choices:
    - "cellranger_multi"
    - "xenium"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_sample_id"
    description: "The key in the h5mu file that contains the sample ID. If not provided,\
      \ each H5MU file will be considered as a separate sample."
    info: null
    default:
    - "sample_id"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_total_counts"
    description: "The key in the h5mu .obs field that contains the total counts."
    info: null
    default:
    - "total_counts"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_num_nonzero_vars"
    description: "The key in the h5mu .obs field that contains the number of nonzero\
      \ vars."
    info: null
    default:
    - "num_nonzero_vars"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_fraction_mitochondrial"
    description: "The key in the h5mu .obs field that contains the fraction mitochondrial\
      \ genes."
    info: null
    default:
    - "fraction_mitochondrial"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_fraction_ribosomal"
    description: "The key in the h5mu .obs field that contains the fraction ribosomal\
      \ genes."
    info: null
    default:
    - "fraction_ribosomal"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output"
    description: "The output JSON file"
    info: null
    example:
    - "path/to/file.json"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output_reporting_json"
    description: "The output JSON file that defines the QC report"
    info: null
    example:
    - "path/to/file.json"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
- name: "Filtering & grouping options"
  arguments:
  - type: "integer"
    name: "--min_total_counts"
    description: "Minimum total counts for a cell to be included in the output"
    info: null
    default:
    - 10
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--min_num_nonzero_vars"
    description: "Minimum number of nonzero vars for a cell to be included in the\
      \ output"
    info: null
    default:
    - 10
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_metadata"
    description: "The metadata keys in the h5mu .obs to include in the output JSON."
    info: null
    example:
    - "donor_id;cell_type;batch;condition"
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
- name: "Options for CellRanger reports"
  arguments:
  - type: "string"
    name: "--obs_cellbender"
    description: "The cellbender keys in the h5mu .obs to include in the output JSON"
    info: null
    default:
    - "cellbender_background_fraction"
    - "cellbender_cell_probability"
    - "cellbender_cell_size"
    - "cellbender_droplet_efficiency"
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--uns_cellranger_metrics"
    description: "The key in the h5mu file .uns that contains the cellranger metrics"
    info: null
    default:
    - "metrics_cellranger"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Options for Xenium reports"
  arguments:
  - type: "string"
    name: "--obs_nucleus_area"
    description: "The key in the h5mu .obs field that contains the nucleus area."
    info: null
    default:
    - "nucleus_area"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_cell_area"
    description: "The key in the h5mu .obs field that contains the cell area."
    info: null
    default:
    - "cell_area"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_x_coord"
    description: "The key in the h5mu .obs field that contains the x coordinate."
    info: null
    default:
    - "x_coord"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_y_coord"
    description: "The key in the h5mu .obs field that contains the y coordinate."
    info: null
    default:
    - "y_coord"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_control_probe_counts"
    description: "The key in the h5mu .obs field that contains the number of control\
      \ probes."
    info: null
    default:
    - "control_probe_counts"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--obs_control_codeword_counts"
    description: "The key in the h5mu .obs field that contains the number of control\
      \ codewords."
    info: null
    default:
    - "control_codeword_counts"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
- type: "file"
  path: "setup_logger.py"
- type: "file"
  path: "report_structure"
- type: "file"
  path: "nextflow_labels.config"
  dest: "nextflow_labels.config"
description: "Takes H5MU files that have been ingested by CellRanger, Xenium or CosMx\
  \ and processed by the QC workflow, and generates:\n- A JSON file that contains\
  \ the combined data for the QC report\n- A JSON file that defines the layout and\
  \ structure of the QC report\n"
test_resources:
- type: "python_script"
  path: "test.py"
  is_executable: true
- type: "file"
  path: "resources_test"
info: null
status: "enabled"
scope:
  image: "private"
  target: "private"
requirements:
  commands:
  - "ps"
repositories:
- type: "github"
  name: "openpipeline"
  repo: "openpipelines-bio/openpipeline"
  tag: "2.1.2"
- type: "vsh"
  name: "craftbox"
  repo: "craftbox"
  tag: "main"
links:
  repository: "https://github.com/openpipelines-bio/openpipeline_incubator"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midmem"
    - "middisk"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1000000000.B"
      mem2gb: "memory = 2000000000.B"
      mem5gb: "memory = 5000000000.B"
      mem10gb: "memory = 10000000000.B"
      mem20gb: "memory = 20000000000.B"
      mem50gb: "memory = 50000000000.B"
      mem100gb: "memory = 100000000000.B"
      mem200gb: "memory = 200000000000.B"
      mem500gb: "memory = 500000000000.B"
      mem1tb: "memory = 1000000000000.B"
      mem2tb: "memory = 2000000000000.B"
      mem5tb: "memory = 5000000000000.B"
      mem10tb: "memory = 10000000000000.B"
      mem20tb: "memory = 20000000000000.B"
      mem50tb: "memory = 50000000000000.B"
      mem100tb: "memory = 100000000000000.B"
      mem200tb: "memory = 200000000000000.B"
      mem500tb: "memory = 500000000000000.B"
      mem1gib: "memory = 1073741824.B"
      mem2gib: "memory = 2147483648.B"
      mem4gib: "memory = 4294967296.B"
      mem8gib: "memory = 8589934592.B"
      mem16gib: "memory = 17179869184.B"
      mem32gib: "memory = 34359738368.B"
      mem64gib: "memory = 68719476736.B"
      mem128gib: "memory = 137438953472.B"
      mem256gib: "memory = 274877906944.B"
      mem512gib: "memory = 549755813888.B"
      mem1tib: "memory = 1099511627776.B"
      mem2tib: "memory = 2199023255552.B"
      mem4tib: "memory = 4398046511104.B"
      mem8tib: "memory = 8796093022208.B"
      mem16tib: "memory = 17592186044416.B"
      mem32tib: "memory = 35184372088832.B"
      mem64tib: "memory = 70368744177664.B"
      mem128tib: "memory = 140737488355328.B"
      mem256tib: "memory = 281474976710656.B"
      mem512tib: "memory = 562949953421312.B"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "python:3.12-slim"
  namespace_separator: "/"
  setup:
  - type: "apt"
    packages:
    - "procps"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "anndata~=0.11.1"
    - "mudata~=0.3.1"
    script:
    - "exec(\"try:\\n  import awkward\\nexcept ModuleNotFoundError:\\n  exit(0)\\\
      nelse:  exit(1)\")"
    upgrade: true
  test_setup:
  - type: "apt"
    packages:
    - "git"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "viashpy==0.8.0"
    github:
    - "openpipelines-bio/core#subdirectory=packages/python/openpipeline_testutils"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/ingestion_qc/h5mu_to_qc_json/config.vsh.yaml"
  runner: "executable"
  engine: "docker"
  output: "target/_private/executable/ingestion_qc/h5mu_to_qc_json"
  executable: "target/_private/executable/ingestion_qc/h5mu_to_qc_json/h5mu_to_qc_json"
  viash_version: "0.9.4"
  git_commit: "41a01155781242d7d1b065c53a1292288230e5eb"
  git_remote: "https://github.com/openpipelines-bio/openpipeline_qc"
package_config:
  name: "openpipeline_incubator"
  version: "build_main"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openpipelines-bio/openpipeline_incubator/resources_test"
      dest: "resources_test"
  repositories:
  - type: "github"
    name: "openpipeline"
    repo: "openpipelines-bio/openpipeline"
    tag: "2.1.2"
  - type: "vsh"
    name: "craftbox"
    repo: "craftbox"
    tag: "main"
  viash_version: "0.9.4"
  source: "src"
  target: "target"
  config_mods:
  - ".requirements.commands := ['ps']\n.runners[.type == 'nextflow'].directives.tag\
    \ := '$id'\n.resources += {path: '/src/configs/labels.config', dest: 'nextflow_labels.config'}\n\
    .runners[.type == 'nextflow'].config.script := 'includeConfig(\"nextflow_labels.config\"\
    )'\n"
  organization: "openpipelines-bio"
  links:
    repository: "https://github.com/openpipelines-bio/openpipeline_incubator"
    docker_registry: "ghcr.io"
