name: detect_ingestion_method
namespace: ingestion_qc
description: | 
  Detects the ingestion method of a dataset.
  Currently detects either 10X CellRanger Multi, 10X Xenium or Nanostring CosMx, but can be extended to other technologies upon request.
authors: 
  - __merge__: /src/authors/dorien_roosen.yaml
    roles: [author]
  - __merge__: /src/authors/weiwei_schultz.yaml
    roles: [contributor]
argument_groups:
  - name: Inputs
    arguments:
      - name: --input
        type: file
        required: true
        direction: input
        description: The input h5mu file(s)
        example: path/to/file.h5mu
      - name: --modality
        type: string
        description: The modality to use
        default: rna
  - name: Outputs
    arguments:
      - name: --output_uns_ingestion_method
        description: The .uns field in which to store the exprimental setup. Values stored are `cellranger_multi`, `xenium` or `cosmx`.
        type: string
        default: ingestion_method
      - name: --output
        type: file
        required: true
        direction: output
        description: The output h5mu file, containing an .uns field with experiment description.
        example: path/to/file.h5mu
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/setup_logger.py
test_resources:
  - type: python_script
    path: test.py
  - path: /resources_test/qc_sample_data/sample_one.qc.h5mu
  - path: /resources_test/spatial_qc_sample_data/Lung5_Rep2_tiny.qc.h5mu
  - path: /resources_test/spatial_qc_sample_data/xenium_tiny.qc.h5mu
engines:
  - type: docker
    image: python:3.12-slim
    setup:
      - type: apt
        packages:
          - procps
      - type: python
        __merge__: [/src/base/requirements/anndata_mudata.yaml]
    test_setup:
    - type: apt
      packages:
        - git
    - type: python
      __merge__: [/src/base/requirements/viashpy.yaml]
      github: openpipelines-bio/core#subdirectory=packages/python/openpipeline_testutils

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [lowmem, lowdisk]
