name: generate_html
namespace: ingestion_qc
description: Generate an HTML report from the QC metrics
authors: 
  - __merge__: /src/authors/jakub_majercik.yaml
    roles: [author]
  - __merge__: /src/authors/dorien_roosen.yaml
    roles: [author]
  - __merge__: /src/authors/robrecht_cannoodt.yaml
    roles: [author]
  - __merge__: /src/authors/weiwei_schultz.yaml
    roles: [contributor]
argument_groups:
  - name: Inputs
    arguments:
      - name: --input_data
        type: file
        required: true
        direction: input
        description: The input JSON file containing the QC metrics
        example: path/to/file.json
      - name: --input_structure
        type: file
        required: true
        direction: input
        description: The input JSON file containing the structure of the data
        example: path/to/file.json
  - name: Outputs
    arguments:
      - name: --output_qc_report
        type: file
        required: true
        direction: output
        description: The output HTML report
        example: path/to/file.html
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - path: /resources_test/qc_sample_data/sc_dataset.json
  - path: /resources_test/qc_sample_data/sc_report_structure.json
  - path: /resources_test/spatial_qc_sample_data/xenium_dataset.json
  - path: /resources_test/spatial_qc_sample_data/xenium_report_structure.json
engines:
  - type: docker
    image: node:latest
    setup:
      - type: apt
        packages:
          - git
      - type: docker
        run: |
          npm install -g pnpm@latest-10 \
          && cd /opt && git clone https://github.com/openpipelines-bio/incubator_ingestion_qc.git \
          && cd incubator_ingestion_qc && pnpm install \
          && true

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [lowmem, lowdisk]
